config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :students
  resources :teachers
  resources :subjects
  resources :lectures
  resources :photos do
    resources :comments
  end
  root 'photos#index'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :photo
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :student
  belongs_to :teacher
end

app/models/photo.rb
class Photo < ApplicationRecord


	has_many_attached :avatars
	has_many :comments, dependent: :destroy

	accepts_nested_attributes_for :comments
	mount_uploader :avatar, AvatarUploader



	def abc
 		"#{description} #{created_at.strftime("%F")}"
 	end
 	
 	
end

app/models/student.rb
class Student < ApplicationRecord
	 has_many :subjects
	 has_many :lectures
	 has_many :teachers, through: :lectures 
end

app/models/subject.rb
class Subject < ApplicationRecord
   has_many :teachers

   belongs_to :student
end

app/models/teacher.rb
class Teacher < ApplicationRecord
	belongs_to :subject
	has_many :lectures
	has_many :students, through: :lectures
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


def create
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.create(comment_params)
    respond_to do |format|
      if @comment.save
        format.html {redirect_to @photo,notice:" successfully created"}
        format.js
      else
        format.html{render:new}
        render :new, status: :unprocessable_entity
      end
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:commentor, :body)
    end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  
  def index
    @lectures = Lecture.all
  end

  def show
    @lecture = Lecture.find(params[:id])
  end


  def new
    @lecture = Lecture.new
  end


  def create
      @lecture = Lecture.new(lecture_params)
      if @lecture.save
          redirect_to @lecture
      else
          render :new, status: :unprocessable_entity
      end
    end

    private
    def lecture_params
      params.require(:lecture).permit(:name,:student_id,:teacher_id)
    end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
   
  
  def index
    @photos=Photo.all
  end


  def show
    @photo = Photo.find(params[:id])
  end


  def new
    @photo = Photo.new
    
    @photo.comments.build
  end

  def create
    @photo = Photo.new(photo_params)
    respond_to do |format|
      if @photo.save
        format.html {redirect_to @photo,notice:"photo successfully created"}
        format.js
      else
        format.html{render:new}
        render :new, status: :unprocessable_entity
      end
    end

  end


  def edit
  @photo = Photo.find(params[:id])
  end


  def update
    @photo = Photo.find(params[:id])

    if @photo.update(photo_params)
      redirect_to @photo
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def photo_params
      params.require(:photo).permit(:description,avatars: [], comments_attributes:[:id,:commentor,:body])
    end



end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	def index
    @students=Student.all
  end


  def show
    @student = Student.find(params[:id])
  end


    def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to @student
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def student_params
      params.require(:student).permit(:name)
    end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

	def index
		@subjects = Subject.all
	end

	def show
		@subject = Subject.find(params[:id])
	end


	def new
		@subject = Subject.new
	end


	def create
  		@subject = Subject.new(subject_params)
    	if @subject.save
      		redirect_to @subject
    	else
      		render :new, status: :unprocessable_entity
    	end
  	end

    private
    def subject_params
      params.require(:subject).permit(:name,:student_id)
    end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

	def index
    @teachers=Teacher.all
  end


  def show
    @teacher = Teacher.find(params[:id])
  end


    def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      redirect_to @teacher
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def teacher_params
      params.require(:teacher).permit(:name, :age,:subject_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/comments/_comment.html.erb
<% @photo.comments.each do |comment| %>


  <p>
    <strong>Commentor:</strong>
    <%= comment.commentor %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
<%end%>
  </p>

app/views/comments/comment.html.erb
<div id="comment_pane" >
  <%= form_with model: [ @photo, @photo.comments.build ],local: false do |form| %>
    <p>
      <%= form.label :commentor %><br>
      <%= form.text_field :commentor %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
</div>

app/views/comments/create.js.erb
$("#comment_pane").append("<%= j render @comment %>");
$("#comment_commentor").val('');
$("#comment_body").val('');

app/views/lectures/index.html.erb
<h1>Lecture</h1>

<ul>
  <% @lectures.each do |lecture| %>
    <li>
      <%= lecture.name %>
  
    </li>
  <% end %>
</ul>

app/views/lectures/new.html.erb
<h1>New Lecture </h1>

<%= form_with model: @lecture do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %></br>

  </div>


 <div>
    <%= form.label :student_id %>
    <%= form.text_field :student_id %>

    
  


   <%= form.select(:student_id, Student.all.collect {|s| [ s.name, s.id ] }, 
                                           { :prompt => "Please select"}
                                           ) %>
    



  </div>



  <div>

    <%= form.label :teacher_id %>
    <%= form.text_field :teacher_id %>

  <%= form.select(:teacher_id, Teacher.all.collect {|s| [ s.name, s.id ] }, 
                                           { :prompt => "Please select"}
                                           ) %>
  </div>

  <div>
  

  
    

    <%= form.submit %>
  <% end %>
</div>

app/views/lectures/show.html.erb
<h1><%= @lecture.name %></h1>
<%= @lecture.teacher.subject.name%></br>
<%= @lecture.teacher.name%></br>
<%=@lecture.student.name%>

app/views/photos/_comments.html.erb
<%=t.label :commentor%>
<%=t.text_field :commentor%>
<%=t.label :body%>
<%=t.text_field :body%>

app/views/photos/_form.html.erb
<%=form_for @photo do |form| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class ="field">
    <% if form.avatar.url%>
        <%= image_tag form.avatar_url,style: 'height:150px;width:auto;'%>
      <%end%>
  </div>
      
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="fields">
    <%=form.fields_for :comments do |t|%>
      <%=t.label :commentor%>
      <%=t.text_field :commentor%>
      <%=t.label :body%>
      <%=t.text_field :body%>
    <%end%>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<%end%>

app/views/photos/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%=link_to "Photo Gallery ", root_path, class:"navbar-brand"%>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%=link_to "New Photo",new_photo_path,class:"navbar-brand"%>   
        </li>
        <li class ="nav-item">
          <%= link_to "New Student",new_student_path,class:"navbar-brand"%></br>
        </li>

        <li class ="nav-item">
          <%= link_to "New Teacher",new_teacher_path,class:"navbar-brand"%>
        </li>

        <li class ="nav-item">
          <%=link_to "New Subject",new_subject_path,class:"navbar-brand"%></br>
        </li>

        <li class ="nav-item">
          <%=link_to "New Lecture",new_lecture_path,class:"navbar-brand"%></br>
        </li>





        <li class ="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path,class:"navbar-brand" %>
        </li>





        <li class ="nav-item">
          <%= link_to 'Sign In', new_user_session_path,class:"navbar-brand" %>
        </li>
          </ul>
        </li>

      </ul>

    </div>
  </div>
</nav>

app/views/photos/edit.html.erb
<h1>Edit Photo</h1>
<%= form_with model: @photo do |form| %>
  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description %>

  </div>
  <%= form.file_field :avatars%>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/index.html.erb
<h1>Photos</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>



  <tbody>
    <% @photos.each do |photo| %>
      <tr id='<%=photo.id%>' >
        <td><%= photo.abc %></td>
        <td>
        <% photo.avatars.each do|f|%>
          <%=image_tag f,style: 'height:150px;width:auto;' %>
        
        <%end%>
      </td>

        <td><%= link_to 'Show', photo_path(photo.id) %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div id="New Photo">

</div>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= form_for @photo do |f| %>
  <div>
    <%= f.label :description %><br>
    <%= f.text_field :description %>

  </div>
  <%= f.label :avatars%>
  <%= f.file_field :avatars, multiple:true%><br/>
  <%=f.fields_for :comments do |p|%>
  <div>
    <%= p.label :commentor%>
    <%= p.text_field :commentor%>
  </div>

  <div>
    <%=p.label :body%>
    <%=p.text_field :body%>
  </div>

  <%end%>
  


  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/new.js.erb
$('# New Photo a').parent().html("<%= j render  'form',photo:@photo%>")

app/views/photos/show.html.erb
<strong>Description</strong>
<h4><%= @photo.description%></h4>
<% if @photo.avatars.attached?%>
<p>
  <strong>Avatars</strong>
  <br>
  <% @photo.avatars.each do |avatar|%>
    <%=image_tag(avatar,style: 'height:200px;width:auto;')%>
  <%end%>
<%end%>



<h2>Comments</h2>
<div id="comment_pane">
<% @photo.comments.each do |comment| %>
 <%= render "comments/comment",local: {comment: @comment}%>
<% end %>
</div>
<h2>Add a comment:</h2>
  <%= form_with model: [ @photo, @photo.comments.build ],local: false do |form| %>
    <p>
      <%= form.label :commentor %><br>
      <%= form.text_field :commentor %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
</div>


</div>



<%= link_to 'edit', edit_photo_path(@photo) %> 

app/views/photos/show.js.erb
alert("photo Created")

app/views/students/index.html.erb
<h1>Students</h1>

<ul>
  <% @students.each do |student| %>
    <li>
      <%= student.name %>
    </li>
  <% end %>
</ul>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= form_with model: @student do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %><br>


  </div>



  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>

app/views/subjects/index.html.erb
<h1>Subjects</h1>

<ul>
  <% @subjects.each do |subject| %>
    <li>
      <%= subject.name %>
  
    </li>
  <% end %>
</ul>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= form_with model: @subject do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %></br>

  </div>


 <div>
    <%= form.label :student_id %>
    <%= form.text_field :student_id %>

    
  


   <%= form.select(:student_id, Student.all.collect {|s| [ s.name, s.id ] }, 
                                           { :prompt => "Please select"}
                                           ) %>
    



  </div>



 
  <div>
  

  
    

    <%= form.submit %>
  <% end %>

app/views/subjects/show.html.erb
<h1><%= @subject.name %></h1>
Student Id
<h1><%=@subject.student_id%><h1>
teacher Id
<h1><%= @subject.teacher_id%>

app/views/teachers/index.html.erb
<h1>Teacher</h1>

<ul>
  <% @teachers.each do |teacher| %>
    <li>
      <%= teacher.name %>
    </li>
  <% end %>
</ul>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= form_with model: @teacher do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>

  </div>
  <div>
    <%= form.label :age%><br/>
    <%= form.text_field :age%>



  <div>


   <div>
    <%= form.label :subject_id%><br/>
    <%= form.text_field :subject_id%>



  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/show.html.erb
<h1><%= @teacher.name %><br>
	<%=@teacher.age%>
</h1>